name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true


jobs:

  kotlin-tests:
    strategy:
      matrix:
        runs-on: [ macos-latest, ubuntu-latest ]
      fail-fast: false
    uses: ./.github/workflows/kotlin-tests.yml
    with:
      runs-on: ${{ matrix.runs-on }}


  build:
    runs-on: macos-latest
    needs: kotlin-tests
    steps:

      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false

      - name: Cache Kotlin Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan/
          key: ${{ runner.os }}-kotlin-konan-${{ hashFiles('**/*.gradle', '**/*.gradle.kts') }}

      - name: Gradle check
        run: ./gradlew check

      - name: Write secrets to local.properties
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo sonatypeUsername="${SONATYPE_USERNAME}" >> "local.properties"
          echo sonatypePassword="${SONATYPE_PASSWORD}" >> "local.properties"
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

      - name: Publish to sonatype
        if: ${{ github.event_name != 'pull_request' }}
        run: ./gradlew publishAllPublicationsToMavenRepository
